blank_issues_enabled: false
contact_links:
  - name: Stravalib community support 
    url: https://github.com/orgs/stravalib/discussions/categories/q-a
    about: Please ask general questions about stravalib in our discussions
