name: Publish to Test PyPI.org
on:
  release:
    types: [published]
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latestgi
    # Only publish from the origin repository, not forks
    if: github.repository_owner == 'stravalib'
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
        with:
          # Ensure scm has enough commits to process version tag
          fetch-depth: 20

      # Build package 
      - run: python3 -m pip install --upgrade build && python3 -m build

            - run: |
          python3 -m pip install --upgrade build && python3 -m build
          echo ""
          echo "Generated files:"
          ls -lh dist/
      - name: Check the archives
        run: twine check dist/*

      - name: Publish package to test pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          # Allow existing releases on test PyPI without errors.
          # NOT TO BE USED in PyPI!
          skip_existing: true

      # This will only happen on release and if everything above works
      - name: Publish package to PyPI
        if: success() && github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          #password: ${{ secrets.PYPI_TOKEN }}
